//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionUI.Recursos.UI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rcsMensajesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rcsMensajesUI() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AplicacionUI.Recursos.UI.rcsMensajesUI", typeof(rcsMensajesUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un canal.
        /// </summary>
        internal static string ErrorProviderSeleccionCanal {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionCanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un destino.
        /// </summary>
        internal static string ErrorProviderSeleccionDestino {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un estrato.
        /// </summary>
        internal static string ErrorProviderSeleccionEstrato {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionEstrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un genero.
        /// </summary>
        internal static string ErrorProviderSeleccionGenero {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un pais de residencia.
        /// </summary>
        internal static string ErrorProviderSeleccionPaisResidencia {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionPaisResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una ubicación.
        /// </summary>
        internal static string ErrorProviderSeleccionUbicacion {
            get {
                return ResourceManager.GetString("ErrorProviderSeleccionUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea salir del programa?.
        /// </summary>
        internal static string MensajeConfirmarSalirPrograma {
            get {
                return ResourceManager.GetString("MensajeConfirmarSalirPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un registro con el número de reserva digitado.
        /// </summary>
        internal static string MensajeErrorDatoNoExisteLista {
            get {
                return ResourceManager.GetString("MensajeErrorDatoNoExisteLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene información para eliminar.
        /// </summary>
        internal static string MensajeErrorPilaVacia {
            get {
                return ResourceManager.GetString("MensajeErrorPilaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro con el número de pasaporte ingresado.
        /// </summary>
        internal static string MensajeRegistroExistenteCola {
            get {
                return ResourceManager.GetString("MensajeRegistroExistenteCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro con el código de reserva digitado.
        /// </summary>
        internal static string MensajeRegistroExistenteLista {
            get {
                return ResourceManager.GetString("MensajeRegistroExistenteLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un registro con el número de identificación ingresado.
        /// </summary>
        internal static string MensajeRegistroExistentePila {
            get {
                return ResourceManager.GetString("MensajeRegistroExistentePila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta de Seguridad.
        /// </summary>
        internal static string ToolbarAlertaBoxSeguridad {
            get {
                return ResourceManager.GetString("ToolbarAlertaBoxSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        internal static string ToolbarAlertaInformativa {
            get {
                return ResourceManager.GetString("ToolbarAlertaInformativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir del programa.
        /// </summary>
        internal static string ToolbarSalirPrograma {
            get {
                return ResourceManager.GetString("ToolbarSalirPrograma", resourceCulture);
            }
        }
    }
}
